#!/bin/sh
#
# shellpki is a wrapper around openssl to manage a small PKI
#

set -e

VERSION="1.0.0"

show_version() {
    cat <<END
shellpki version ${VERSION}

Copyright 2010-2019 Evolix <info@evolix.fr>,
                    Thomas Martin <tmartin@evolix.fr>,
                    Gregory Colpart <reg@evolix.fr>,
                    Romain Dessort <rdessort@evolix.fr>,
                    Benoit Série <bserie@evolix.fr>,
                    Victor Laborie <vlaborie@evolix.fr>,
                    Daniel Jakots <djakots@evolix.fr>,
                    Patrick Marchand <pmarchand@evolix.fr>,
                    Jérémy Lecour <jlecour@evolix.fr>
                    and others.

shellpki comes with ABSOLUTELY NO WARRANTY.  This is free software,
and you are welcome to redistribute it under certain conditions.
See the MIT Licence for details.
END
}

init() {
    umask 0177

    [ -d "${CADIR}" ] || mkdir -m 0750 "${CADIR}"
    [ -d "${CRTDIR}" ] || mkdir -m 0750 "${CRTDIR}"
    [ -f "${INDEX}" ] || touch "${INDEX}"
    [ -f "${CRL}" ] || touch "${CRL}"
    [ -f "${SERIAL}" ] || echo "01" > "${SERIAL}"

    cn="${1:-}"
    if [ -z "${cn}" ]; then
        show_usage >&2
        exit 1
    fi

    if [ -f "${CAKEY}" ]; then
        printf "%s already exists, do you really want to erase it ? [y/N] " "${CAKEY}"
        read -r REPLY
        resp=$(echo "${REPLY}" | tr 'Y' 'y')
        if [ "${resp}" = "y" ]; then
            rm -f "${CAKEY}" "${CACERT}"
        fi
    fi

    if [ ! -f "${CAKEY}" ]; then
        "$OPENSSL" genrsa \
            -out "${CAKEY}" \
            -aes256 4096 \
            >/dev/null 2>&1
    fi

    if [ -f "${CACERT}" ]; then
        printf "%s already exists, do you really want to erase it ? [y/N] " "${CACERT}"
        read -r REPLY
        resp=$(echo "${REPLY}" | tr 'Y' 'y')
        if [ "${resp}" = "y" ]; then
            rm "${CACERT}"
        fi
    fi

    if [ ! -f "${CACERT}" ]; then
        ask_ca_password 0
    fi

    if [ ! -f "${CACERT}" ]; then
        CA_PASSWORD="${CA_PASSWORD}" "${OPENSSL}" req \
            -new \
            -batch \
            -sha512 \
            -x509 \
            -days 3650 \
            -extensions v3_ca \
            -key "${CAKEY}" \
            -out "${CACERT}" \
            -passin env:CA_PASSWORD \
            -config /dev/stdin <<EOF
$(cat "${CONFFILE}")
commonName_default = ${cn}
EOF
    fi
}

ocsp() {
    umask 0177

    ocsp_uri="${1:-}"
    if [ -z "${ocsp_uri}" ]; then
        show_usage >&2
        exit 1
    fi

    url=$(echo "${ocsp_uri}" | cut -d':' -f1)
    port=$(echo "${ocsp_uri}" | cut -d':' -f2)

    if [ ! -f "${OCSPKEY}" ]; then
        "$OPENSSL" genrsa \
            -out "${OCSPKEY}" \
            2048 \
            >/dev/null 2>&1
    fi

    "$OPENSSL" req \
        -batch \
        -new \
        -key "${OCSPKEY}" \
        -out "${CSRDIR}/ocsp.csr" \
        -config /dev/stdin <<EOF
$(cat "${CONFFILE}")
commonName_default = ${url}
[ usr_cert ]
authorityInfoAccess = OCSP;URI:http://${ocsp_uri}
EOF

    if [ ! -f "${OCSPCERT}" ]; then
        ask_ca_password 0
    fi

    if [ ! -f "${OCSPCERT}" ]; then
        CA_PASSWORD="${CA_PASSWORD}" "${OPENSSL}" ca \
            -extensions v3_ocsp \
            -in "${CSRDIR}/ocsp.csr" \
            -out "${OCSPCERT}" \
            -passin env:CA_PASSWORD \
            -config "${CONFFILE}"
    fi

    exec "${OPENSSL}" ocsp \
        -ignore_err \
        -index "${INDEX}" \
        -port "${port}" \
        -rsigner "${OCSPCERT}" \
        -rkey "${OCSPKEY}" \
        -CA "${CACERT}" \
        -text
}

show_usage() {
    cat <<EOF
Usage: ${0} <subcommand> [options] [CommonName]

Initialize PKI (create CA key and self-signed cert) :

    ${0} init <commonName_for_CA>

Run OCSPD server :

    ${0} ocsp <ocsp_uri:ocsp_port>

Create a client cert with key and CSR directly generated on server
(use -p or --password-file to set a password on the client key) :

    ${0} create [-p|--password-file=<FILE>] <commonName>

Create a client cert from a CSR (doesn't need key) :

    ${0} create -f <path>

Revoke a client cert with is commonName (CN) :

    ${0} revoke <commonName>

List all actually valid commonName (CN) :

    ${0} list [-a|v|r]

Check expiration date of valid certificates :

    ${0} check

EOF
}

error() {
    echo "${1}" >&2
    exit 1
}

warning() {
    echo "${1}" >&2
}

ask_ca_password() {
    [ ! -f "${CAKEY}" ] && error "You must initialize your's PKI with shellpki init !"
    attempt=$((${1} + 1))
    if [ "${attempt}" -gt 1 ]; then
        warning "Invalid password, retry."
    fi
    trap 'unset CA_PASSWORD' 0
    stty -echo
    printf "Password for CA key : "
    read -r CA_PASSWORD
    stty echo
    printf "\n"

    if [ -z "${CA_PASSWORD}" ]; then
        ask_ca_password "${attempt}"
    fi
    CA_PASSWORD="${CA_PASSWORD}" "${OPENSSL}" rsa \
        -in "${CAKEY}"    \
        -passin env:CA_PASSWORD \
        >/dev/null 2>&1 \
    || ask_ca_password "${attempt}"
}

create() {
    from_csr=0
    ask_pass=0

    # Parse options
    # based on https://gist.github.com/deshion/10d3cb5f88a21671e17a
    while :; do
        case $1 in
            -f|--file|--csr-file)
                # csr-file option, with value separated by space
                if [ -n "$2" ]; then
                    from_csr=1
                    csr_file=$(readlink -f -- "${2}")
                    shift
                else
                    printf 'ERROR: "--csr-file" requires a non-empty option argument.\n' >&2
                    exit 1
                fi
                ;;
            --file=?*|--csr-file=?*)
                from_csr=1
                # csr-file option, with value separated by =
                csr_file=$(readlink -f -- "${1#*=}")
                ;;
            --file=|--csr-file=)
                # csr-file options, without value
                printf 'ERROR: "--csr-file" requires a non-empty option argument.\n' >&2
                exit 1
                ;;
            -p|--password)
                ask_pass=1
                ;;
            --password-file)
                # password-file option, with value separated by space
                if [ -n "$2" ]; then
                    password_file=$(readlink -f -- "${2}")
                    shift
                else
                    printf 'ERROR: "--password-file" requires a non-empty option argument.\n' >&2
                    exit 1
                fi
                ;;
            --password-file=?*)
                # password-file option, with value separated by =
                password_file=$(readlink -f -- "${1#*=}")
                ;;
            --password-file=)
                # password-file options, without value
                printf 'ERROR: "--password-file" requires a non-empty option argument.\n' >&2
                exit 1
                ;;
            --)
                # End of all options.
                shift
                break
                ;;
            -?*)
                # ignore unknown options
                printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
                ;;
            *)
                # Default case: If no more options then break out of the loop.
                break
                ;;
        esac

        shift
    done

    cn="${1:-}"

    if [ "${from_csr}" -eq 1 ]; then
        if [ "${ask_pass}" -eq 1 ]; then
            warning "Warning: -p|--password is ignored with -f|--file|--crt-file"
        fi
        if [ -n "${password_file}" ]; then
            warning "Warning: --password-file is ignored with -f|--file|--crt-file"
        fi

        # ask for CA passphrase
        ask_ca_password 0

        # check if csr_file is a CSR
        "${OPENSSL}" req \
            -noout -subject \
            -in "${csr_file}" \
            >/dev/null 2>&1 \
        || error "${csr_file} is not a valid CSR !"

        # check if csr_file contain a CN
         "${OPENSSL}" req \
            -noout -subject         \
            -in "${csr_file}" \
            | grep -Eo "CN\s*=[^,/]*" \
            >/dev/null 2>&1 \
        || error "${csr_file} don't contain a CommonName !"

        # get CN from CSR
        cn=$("${OPENSSL}" req -noout -subject -in "${csr_file}" | grep -Eo "CN\s*=[^,/]*" | cut -d'=' -f2 | xargs)

        # check if CN already exist
        if [ -f "${CRTDIR}/${cn}.crt" ]; then
            error "${cn} already used !"
        fi

        # ca sign and generate cert
        CA_PASSWORD="${CA_PASSWORD}" "${OPENSSL}" ca \
            -config "${CONFFILE}" \
            -in "${csr_file}" \
            -passin env:CA_PASSWORD \
            -out "${CRTDIR}/${cn}.crt"

        echo "The CRT file is available in ${CRTDIR}/${cn}.crt"
    else
        if [ -z "${cn}" ]; then
            show_usage >&2
            exit 1
        fi

        # check if CN already exist
        if [ -f "${CRTDIR}/${cn}.crt" ]; then
            error "${cn} already used !"
        fi

        # ask for CA passphrase
        ask_ca_password 0

        if [ -n "${password_file}" ] && [ -r "${password_file}" ]; then
            PASSWORD=$(head -n 1 "${password_file}" | tr -d '\n')
            if [ -z "${PASSWORD}" ]; then
                warning "Warning: empty password from file \`${password_file}'"
            fi
        elif [ "${ask_pass}" -eq 1 ]; then
            trap 'unset PASSWORD' 0
            stty -echo
            printf "Password for user key : "
            read -r PASSWORD
            stty echo
            printf "\n"

            if [ -z "${PASSWORD}" ]; then
                warning "Warning: empty password from input"
            fi
        fi

        # generate private key
        if [ -n "${PASSWORD}" ]; then
            PASSWORD="${PASSWORD}" "$OPENSSL" genrsa \
                -aes256 \
                -passout env:PASSWORD \
                -out "${KEYDIR}/${cn}-${TIMESTAMP}.key" \
                2048 \
                >/dev/null 2>&1
        else
            "$OPENSSL" genrsa                           \
                -out "${KEYDIR}/${cn}-${TIMESTAMP}.key" \
                2048 \
                >/dev/null 2>&1
        fi

        if [ -n "${PASSWORD}" ]; then
            # generate csr req
            PASSWORD="${PASSWORD}" "$OPENSSL" req \
                -batch \
                -new \
                -key "${KEYDIR}/${cn}-${TIMESTAMP}.key" \
                -passin env:PASSWORD \
                -out "${CSRDIR}/${cn}-${TIMESTAMP}.csr" \
                -config /dev/stdin <<EOF
$(cat "${CONFFILE}")
commonName_default = ${cn}
EOF
        else
            # generate csr req
            "$OPENSSL" req \
                -batch \
                -new \
                -key "${KEYDIR}/${cn}-${TIMESTAMP}.key" \
                -out "${CSRDIR}/${cn}-${TIMESTAMP}.csr" \
                -config /dev/stdin <<EOF
$(cat "${CONFFILE}")
commonName_default = ${cn}
EOF
        fi

        # ca sign and generate cert
        CA_PASSWORD="${CA_PASSWORD}" "${OPENSSL}" ca \
            -config "${CONFFILE}" \
            -passin env:CA_PASSWORD \
            -in "${CSRDIR}/${cn}-${TIMESTAMP}.csr" \
            -out "${CRTDIR}/${cn}.crt"

        # check if CRT is a valid
        "${OPENSSL}" x509 \
            -noout \
            -subject \
            -in "${CRTDIR}/${cn}.crt" \
            >/dev/null 2>&1 \
        || rm -f "${CRTDIR}/${cn}.crt"

        if [ ! -f "${CRTDIR}/${cn}.crt" ]; then
            error "Error in CSR creation"
        fi

        chmod 640 "${CRTDIR}/${cn}.crt"

        echo "The CRT file is available in ${CRTDIR}/${cn}.crt"

        # generate pkcs12 format
        if [ -n "${PASSWORD}" ]; then
            PASSWORD="${PASSWORD}" "${OPENSSL}" pkcs12 \
                -export \
                -nodes \
                -passin env:PASSWORD \
                -passout env:PASSWORD \
                -inkey "${KEYDIR}/${cn}-${TIMESTAMP}.key" \
                -in "${CRTDIR}/${cn}.crt" \
                -out "${PKCS12DIR}/${cn}-${TIMESTAMP}.p12"
        else
             "${OPENSSL}" pkcs12 \
                 -export \
                 -nodes \
                 -passout pass: \
                 -inkey "${KEYDIR}/${cn}-${TIMESTAMP}.key" \
                 -in "${CRTDIR}/${cn}.crt" \
                 -out "${PKCS12DIR}/${cn}-${TIMESTAMP}.p12"
        fi

        chmod 640 "${PKCS12DIR}/${cn}-${TIMESTAMP}.p12"
        echo "The PKCS12 config file is available in ${PKCS12DIR}/${cn}-${TIMESTAMP}.p12"

        # generate openvpn format
        if [ -e "${CADIR}/ovpn.conf" ]; then
            cat "${CADIR}/ovpn.conf" - > "${OVPNDIR}/${cn}-${TIMESTAMP}.ovpn" <<EOF
<ca>
$(cat "${CACERT}")
</ca>

<cert>
$(cat "${CRTDIR}/${cn}.crt")
</cert>

<key>
$(cat "${KEYDIR}/${cn}-${TIMESTAMP}.key")
</key>
EOF
            chmod 640 "${OVPNDIR}/${cn}-${TIMESTAMP}.ovpn"
            echo "The OpenVPN config file is available in ${OVPNDIR}/${cn}-${TIMESTAMP}.ovpn"
        fi
    fi
}

revoke() {
    if [ "${1}" = "" ]; then
        show_usage >&2
        exit 1
    fi

    # get CN from param
    cn="${1}"

    # check if CRT exists
    if [ ! -f "${CRTDIR}/${cn}.crt" ]; then
        error "Unknow CN : ${cn}"
    fi

    # check if CRT is a valid
    "${OPENSSL}" x509 \
        -noout \
        -subject \
        -in "${CRTDIR}/${cn}.crt" \
        >/dev/null 2>&1 \
    || error "${CRTDIR}/${cn}.crt is not a valid CRT, you must delete it !"

    # ask for CA passphrase
    ask_ca_password 0

    echo "Revoke certificate ${CRTDIR}/${cn}.crt :"
    CA_PASSWORD="${CA_PASSWORD}" "$OPENSSL" ca \
        -config "${CONFFILE}" \
        -passin env:CA_PASSWORD \
        -revoke "${CRTDIR}/${cn}.crt" \
    && rm "${CRTDIR}/${cn}.crt"

    CA_PASSWORD="${CA_PASSWORD}" "$OPENSSL" ca \
        -config "${CONFFILE}" \
        -passin env:CA_PASSWORD \
        -gencrl -out "${CRL}"
}

list() {
    if [ ! -f "${INDEX}" ]; then
        exit 0
    fi

    list_valid=0
    list_revoked=1

    while :; do
        case "${1}" in
            -a|--all)
                list_valid=0
                list_revoked=0
                shift;;
            -v|--valid)
                list_valid=0
                list_revoked=1
                shift;;
            -r|--revoked)
                list_valid=1
                list_revoked=0
                shift;;
            --)
                shift
                break;;
            -?*)
                warning "unknow option ${1} (ignored)"
                shift;;
            *)
                break;;
        esac
    done

    if [ "${list_valid}" -eq 0 ]; then
        certs=$(grep "^V" "${INDEX}")
    fi

    if [ "${list_revoked}" -eq 0 ]; then
        certs=$(grep "^R" "${INDEX}")
    fi

    if [ "${list_valid}" -eq 0 ] && [ "${list_revoked}" -eq 0 ]; then
        certs=$(cat "${INDEX}")
    fi

    echo "${certs}" | grep -Eo "CN\s*=[^,/]*" | cut -d'=' -f2 | xargs -n1
}

check() {
    # default expiration alert
    # TODO : permit override with parameters
    min_day=90
    cur_epoch=$(date -u +'%s')

    for cert in ${CRTDIR}/*; do
        end_date=$(openssl x509 -noout -enddate -in "${cert}" | cut -d'=' -f2)
        end_epoch=$(date -ud "${end_date}" +'%s')
        diff_epoch=$((end_epoch - cur_epoch))
        diff_day=$((diff_epoch/60/60/24))
        if [ "${diff_day}" -lt "${min_day}" ]; then
            if [ "${diff_day}" -le 0 ]; then
                echo "${cert} has expired"
            else
                echo "${cert} expire in ${diff_day} days"
            fi
        fi
    done
}

main() {
    # default config
    # TODO : override with /etc/default/shellpki
    CONFFILE="/etc/shellpki/openssl.cnf"

    if [ "$(uname)" = "OpenBSD" ]; then
        PKIUSER="_shellpki"
    else
        PKIUSER="shellpki"
    fi

    if [ "${USER}" != "root" ] && [ "${USER}" != "${PKIUSER}" ]; then
        error "Please become root before running ${0} !"
    fi

    # retrieve CA path from config file
    CADIR=$(grep -E "^dir" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1)
    CAKEY=$(grep -E "^private_key" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1 | sed "s~\$dir~${CADIR}~")
    CACERT=$(grep -E "^certificate" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1 | sed "s~\$dir~${CADIR}~")
    OCSPKEY="${CADIR}/ocsp.key"
    OCSPCERT="${CADIR}/ocsp.pem"
    CRTDIR=$(grep -E "^certs" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1 | sed "s~\$dir~${CADIR}~")
    TMPDIR=$(grep -E "^new_certs_dir" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1 | sed "s~\$dir~${CADIR}~")
    INDEX=$(grep -E "^database" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1 | sed "s~\$dir~${CADIR}~")
    SERIAL=$(grep -E "^serial" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1 | sed "s~\$dir~${CADIR}~")
    CRL=$(grep -E "^crl" "${CONFFILE}" | cut -d'=' -f2 | xargs -n1 | sed "s~\$dir~${CADIR}~")

    # directories for clients key, csr, crt
    KEYDIR="${CADIR}/private"
    CSRDIR="${CADIR}/requests"
    PKCS12DIR="${CADIR}/pkcs12"
    OVPNDIR="${CADIR}/openvpn"

    OPENSSL=$(command -v openssl)
    TIMESTAMP=$(/bin/date +"%s")

    if ! getent passwd "${PKIUSER}" >/dev/null || ! getent group "${PKIUSER}" >/dev/null; then
        error "You must create ${PKIUSER} user and group !"
    fi

    if [ ! -e "${CONFFILE}" ]; then
        error "${CONFFILE} is missing"
    fi

    mkdir -p "${CADIR}" "${CRTDIR}" "${KEYDIR}" "${CSRDIR}" "${PKCS12DIR}" "${OVPNDIR}" "${TMPDIR}"

    command=${1:-help}

    case "${command}" in
        init)
            shift
            init "$@"
        ;;

        ocsp)
            shift
            ocsp "$@"
        ;;

        create)
            shift
            create "$@"
        ;;

        revoke)
            shift
            revoke "$@"
        ;;

        list)
            shift
            list "$@"
        ;;

        check)
            shift
            check "$@"
        ;;

        version)
            show_version
            exit 0
        ;;

        help)
            show_usage
            exit 0
        ;;

        *)
            show_usage >&2
            exit 1
        ;;
    esac

    # fix right
    chown -R "${PKIUSER}":"${PKIUSER}" "${CADIR}"
    chmod 750 "${CADIR}" "${CRTDIR}" "${KEYDIR}" "${CSRDIR}" "${PKCS12DIR}" "${OVPNDIR}" "${TMPDIR}"
    chmod 600 "${INDEX}"* "${SERIAL}"* "${CAKEY}" "${CRL}"
    chmod 640 "${CACERT}"
}

main "$@"
